name: Continuous Integration of gas-sample with jest

run-name: ${{ github.actor }} is testing out gas-sample with jest

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Branch Check
        run: |
          echo Branch: ${{ github.head_ref }}
      - name: Run Jest
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          test-script: npx jest --coverage --silent --testLocationInResults --ci --json --outputFile=report.json
